main: net.bcloud.bengine.bEngine

name: bEngine
description: Engine support for developer to code faster.
version: '${project.version}'
author: Bluismine

api-version: 1.18
load: STARTUP

softdepend: [PlaceholderAPI]

# List of plugins using bEngine ( I recommend add your plugins in here )
loadbefore:
  - RegalEconomy
#  - bCloud
